# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 16:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='식당이름')),
                ('image', models.ImageField(default='/Users/jihun/eatcha_project_배포연습용/media/default.jpeg', upload_to='')),
                ('content', models.TextField(default='내용없음', max_length=500, null=True, verbose_name='내용')),
                ('menu', models.TextField(default='메뉴 정보 없음', max_length=500, null=True, verbose_name='메뉴 가격')),
                ('avail_time', models.TextField(default='영업시간 정보 없음', max_length=300, verbose_name='영업 시간')),
                ('lnglat', models.CharField(blank=True, max_length=100, verbose_name='식당위치')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('score', models.SmallIntegerField(default=-1)),
                ('phone_number', models.TextField(default='전화번호 정보 없음', max_length=15, verbose_name='전화번호')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('menu', models.TextField(default='메뉴정보 없음', max_length=300, verbose_name='메뉴와 가격')),
                ('avg_price', models.PositiveIntegerField(default=-1)),
                ('score', models.CharField(default=-1, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
