# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171012_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/jihun/eatcha_project_배포연습용/media/default.jpeg', upload_to=''),
        ),
    ]
