# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171012_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_content1',
            field=models.TextField(default='내용없음', max_length=500, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_content2',
            field=models.TextField(default='내용없음', max_length=500, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_content3',
            field=models.TextField(default='내용없음', max_length=500, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_title1',
            field=models.CharField(default='내용없음', max_length=100, verbose_name='블로그1'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_title2',
            field=models.CharField(default='내용없음', max_length=100, verbose_name='블로그2'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_title3',
            field=models.CharField(default='내용없음', max_length=100, verbose_name='블로그2'),
        ),
        migrations.AddField(
            model_name='post',
            name='link1',
            field=models.CharField(default='내용없음', max_length=200, verbose_name='링크1'),
        ),
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.CharField(default='내용없음', max_length=200, verbose_name='링크2'),
        ),
        migrations.AddField(
            model_name='post',
            name='link3',
            field=models.CharField(default='내용없음', max_length=200, verbose_name='링크3'),
        ),
    ]
