# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171014_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_title1',
            field=models.CharField(default='내용없음', max_length=200, verbose_name='블로그1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_title2',
            field=models.CharField(default='내용없음', max_length=200, verbose_name='블로그2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_title3',
            field=models.CharField(default='내용없음', max_length=200, verbose_name='블로그2'),
        ),
    ]
