# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_post_content3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number',
        ),
        migrations.AddField(
            model_name='post',
            name='avail_time',
            field=models.TextField(default='영업시간 정보 없음', max_length=300, verbose_name='영업 시간'),
        ),
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.TextField(default='메뉴 정보 없음', max_length=500, verbose_name='메뉴 가격'),
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.TextField(default='전화번호 정보 없음', max_length=15, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='내용없음', max_length=500, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/jihun/git_practice/eatcha_project/eatcha_project/media/default.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
