# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171014_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_title2',
            field=models.CharField(default='내용없음', max_length=200, null=True, verbose_name='블로그2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_title3',
            field=models.CharField(default='내용없음', max_length=200, null=True, verbose_name='블로그2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link2',
            field=models.CharField(default='내용없음', max_length=200, null=True, verbose_name='링크2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link3',
            field=models.CharField(default='내용없음', max_length=200, null=True, verbose_name='링크3'),
        ),
    ]
