# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20171014_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/joon/Documents/hanium/media/default.jpeg', upload_to=''),
        ),
    ]
