# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170830_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/jihun/eatcha_project_배포연습용/media/default.jpeg', upload_to=''),
        ),
    ]
