# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170817_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='내용없음', max_length=500, null=True, verbose_name='내용'),
        ),
    ]
