# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170817_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/jihun/hanium/media/default.jpeg', upload_to=''),
        ),
    ]
