# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171004_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='avg_price',
            field=models.CharField(default=-1, max_length=50),
        ),
    ]
