# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170826_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag2',
            old_name='name2',
            new_name='name',
        ),
    ]
