# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170826_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag2',
        ),
    ]
